project_id = "lrgljpjmugzcmddizskh"

[functions.ai-photo-rename]
verify_jwt = true

[functions.ai-docs-search]
verify_jwt = false

[functions.log-error]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false