project_id = "lrgljpjmugzcmddizskh"

[functions.get-weather]
verify_jwt = false

[functions.ai-photo-rename]
verify_jwt = true

[functions.ai-docs-search]
verify_jwt = false

[functions.log-error]
verify_jwt = false